### PR TITLE
Better implementation

### PR DESCRIPTION
**Pull request by bgottsch**
Hi @pdlove ,

I came across your plugin and made some changes to improve it.

- removed fan service
- modified thermostat service
- fixed some value limits
- added battery status

I removed the _fan_ service because it was too confusing in combination with a thermostat. On the thermostat service I added characteristics to replace the functionality before provided by the _fan_ service. The switch characteristic is not present because the ```TargetHeatingCoolingState``` characteristic already has the option to accept the _off_ state. ```CurrentHeatingCoolingState``` reflects this.

The problem I ran into was with the _fan_ mode supported by Sensibo. Since HomeKit does not support the _fan_ mode in the ```TargetHeatingCoolingState``` characteristic on a thermostat, I made the _auto_ mode correspond to the _fan_ functionality os Sensibo. Also, since ```CurrentHeatingCoolingState``` does not support an _auto_ or _fan_ mode, every time you turn on the _fan_ mode, this characteristic displays _cooling_.

About the value limits, I added some code to limit the temperature changes to accept Sensibo's limits: ```16˚C to 30˚C```.

Finally, I added a battery characteristic and implemented the api to support the request. The values range from a max of ```3000mV (3V)``` to a min of ```2600mV (2.6V)```. The displayed value on HomeKit is the percentage between these limits. I use the formula ``` voltage% = (currentVoltage - minVoltage) / (maxVoltage - minVoltage)```.

Regarding Siri use, I am still having trouble with the turning on/off using the ```TargetHeatingCoolingState``` and controlling the fan speed using the ```RotationSpeed``` characteristic in the thermostat service. I'll see if I can get around this.

I hope you like the changes.

Best regards,
Beno

### CODE REVIEW

**Comment by leoneleone** [comment]
@bgottsch 

Thanks for all the work. I'll have a chance to look at this and try it out later today or tomorrow. 

I've thought about integrating everything under the Thermostat service. You are right, turning the pod on/off used to work via Siri before Apple made some recent changes to the server side of HomeKit. 

Rotation Speed being under Service.Fan actually work for Siri commands. I have it set up so the Fan part has a unique name in HomeKit: Living Room AC Fan, for example. I can say: "Set the Living Room AC Fan to high/low" and Siri understands the commands and executes it. 

I'll give your code a test and let you know what I find regarding Siri commands. 

Thanks again!!

**Comment by bgottsch** [comment]
@leoneleone 

I've been messing around with the HomeKit Accessory Simulator on my Mac, and Siri does not seem to be able to control the `TargetHeatingCoolingState`, which should be the correct implementation for turning on/off and selecting the operational mode.

About the `RotationSpeed`, I was only able to change the speed with Siri on a fan service. When I add this characteristic to the thermostat service, Siri does not recognise it.

I'll try to think of other possible solutions, but I believe that with the changes made on this branch the implementation will be at its best, HomeKit speaking. I think Siri is the one with problems here. Many features from HomeKit seem to fail in Siri, and I think Apple wi'll fix this in the future (hopefully on WWDC 16'). Let's hope they make an Air Conditioner service. So for now, while Siri is still having problems, I would suggest using the most correct way of implementing Sensibo into HomeKit.

**Comment by bgottsch** [comment]
@leoneleone 

I found something. Siri is able to set the temperature of a thermostat. I believe Apple intended it that way, since a smart thermostat basically controls only the temperature, and adjusts the required mode as according. For example, if my room is at 22˚ and I want it to go to 23˚, the thermostat would turn on the heater mode. But if my room is at 24˚ and I want it to go to 20˚, it would turn on the cooling mode. We could adapt this logic and set the TargetHeatingCoolingState based on the requested temperature.

I still need to figure how to turn if on or off, and how to use the fan functionality.

**Comment by leoneleone** [comment]
@bgottach:

Look at the optional Characteristic HeatingCoolingThreshold for that functionality.

**Comment by bgottsch** [comment]
@leoneleone I will submit a new version I've been working last night. I changed the implementation to have three services: thermostat, fan and humidity sensor. This way, Siri can work better with the accessory.

The only issue I had was to make Siri control the `TargetHeatingCoolingState`, so to go around this issue, I created a simple logic where depending on the current temperature and the target temperature, it sets the mode to cool or heat, and turns on the A/C. I still am working on the implementation, but I think we had amazing progress.

Also, in this version, I fixed the console output to look similar to homebridge's output.

About the `HeatingThresholdTemperature` and `CoolingThresholdTemperature`, what exactly is your idea with them?

**Comment by leoneleone** [comment]
HeatingThresholdTemp: the temperature at which the thermostat switches to HEAT

CoolingThresholdTemp: the temperature at which the thermostat switches to COOL

It provides the logic you are looking for 😊

**Comment by bgottsch** [comment]
@leoneleone 

Awesome! I will implement those characteristics as soon as I can. With this, I think the plugin will be better than ever. You will have voice control for the important, everyday and Siri supported features, as well as control of other features in the HomeKit platform by using an app. By implementing a threshold it will be able to customize the temperature in which it should set the mode as heater or cooler. Integrated with turning on by setting the temperature, it would be great.

Off topic, I was wondering about dynamic plugins (plugin 2.0), a new feature implemented this year to homebridge. I don't think this plugin currently supports it, and it would be a great feature to support, since it would allow pods to be added and removed dynamically, without restarting homebridge. Let me know about your view of plugin 2.0

**Comment by leoneleone** [comment]
Yes, making this a dynamic plugin would be quite useful. 
Having said that, I really don't see people adding a new Sensibo pod on a regular basis. It would be nice, but of limited use in my opinion.

**Comment by leoneleone** [comment]
I am actually planning to add a new AC in my flat. Just waiting for a HomeKit compatible one to come onto the market. Otherwise I might buy a Haier Air-D (HomeKit compatible AC) from China and have it shipped over 😊 

The Dyson Cool Links look very interesting, but I'd have to write a new plugin to make that work with Homebridge 😔

**Comment by bgottsch** [comment]
@leoneleone 

Sounds nice. I would suggest waiting for WWDC, since they could add a air conditioner accessory.

About the dynamic functionality. I was looking into it and I agree with you. Practically it would have no use. A dynamic plugin, if I'm not mistaken, was intended to interface with systems where a device needs to be removed or added on run time. Also, I don't think the Sensibo API has the functionality to send events such as new pods. In their API, the client should make requests to the server about new info. The server should not update the client as this plugin 2.0 was intended. The workaround would be  for the plugin to refresh every x seconds, but it would be bad practice. Maybe it's best not to make this a dynamic plugin.

Off topic here.

I also developed an Insteon Hub plugin (https://github.com/bgottsch/homebridge-insteonScene), and I'm finishing a few touches to it. It controls scenes only, and works like the Hamorny Hub plugin, thought way simpler.

I was thinking of developing a plugin which would restart the server when turned on. I still need to figure how to make a child process terminate and initiate a parent process. Also, I need to see how it would work in conjunction with systemd on a Raspberry Pi (my setup). An idea I had was to enable auto restart on the systemd process and simply elaborate a way for the plugin to kill homebridge. Then, the systemd would restart it again.

**Comment by bgottsch** [comment]
Done with the threshold temperature feature. Now there's a new characteristic in the thermostat (CoolingThresholdTemperature) which is the temperature you would like the modes heat/cool to change. 

For example, my threshold is 24˚ and my current temperature is 21˚. Before, if I set my target temperature to 22˚ it would switch to heat mode, which made no sense for setting the A/C to a "less calling temperature". Now, if I set my target temperature to 22˚, it will set the mode to cool. If i set it to 24˚, the mode will be cool still, but for values above the threshold, it would change the mode to heat.

For colder days, you can change manually via the app the threshold to say 22˚ and every temperature set above (not >=) will change the A/C mode to heat.

This is still not the ideal approach, but as we are limited to what Apple allows us to do and with Siri being so weak in controlling HomeKit, this is the most user-friendly approach for using Siri to control Sensibo.

Thanks to @leoneleone for the idea.

@pdlove some testing is still necessary, but I believe this PR is almost ready to be merged.

**Comment by pdlove** [comment]
@bgottsch sounds good. I'll merge when ready. I actually wrote this plugin as a favor for a friend and don't have a Sensibo of my own. I'll also be excited when Apple gets a better set of services for air conditioners. I've had to do some odd hacks to get Siri working as expected with my thermostat.
The dynamic functionality works very well for hubs. With Sensibo, it would require polling the device list ever so often and creating or removing the appropriate device.
I've given up on HomeKit for the time being. Until Apple creates a hub to manage triggers rather than relying one my phone, it is kinda useless to me.

**Comment by bgottsch** [comment]
@pdlove I agree. HomeKit is still years away of whats expected. A/C functionality is essential and they don't support it. Non iPhone control and triggers also. Even a Mac can't control HomeKit. Hope they take a step on WWDC '16 because this is far from good.

I don't know if you ever used the hack SiriProxy before Apple prohibited it. It worked before iOS 7 was even released and still allowed for more functionality than HomeKit, even being a hack.

Regards,
Beno

**Comment by bgottsch** [comment]
Well, I just watched WWDC '16 and it seems there is now support for A/C's in HomeKit. Since the new features are still in beta, I don't believe they will be able to be implemented now or anytime soon. Also, the homebridge platform should be updated to support it.

For the mean time, it's best to wait for everything to be released. But when it is, this plugin would work a lot better.

**Comment by leoneleone** [comment]
iOS 10 beta 2 and still no details about the AC Service Type and its Characteristics. I guess we have to wait until a future beta before we can integrate the plugin under the new Service Type. 

Siri, on the other hand, seems to be working better. 
I can turn the pods ON and Off using Siri Voice Commands, just like it worked before.

**Comment by leoneleone** [comment]
@bgottsch 
Sorry for taking a month to test your code. Finally got you revisions installed on my system.

I have some observations:

- The battery level does not show up for me in HomeKit. I don't see the battery in indicator in Eve app, which would usually show such info. It does appear when I use the latest version of HomeKit Catalog from the Apple Dev website though. Maybe this has to do with the HomeKit Server side and how it displays the BatteryStatus characteristic. We might have to modify a few things once iOS 10 is officially released.

- I prefer if all Characteristics are all under one ServiceType (Thermostat), including Rotation Speed, and RelativeHumidity. Since iOS 10 beta 4 HomeKit seems to accept adding any characteristics to any service type. There had been some limitations with that recently, but now HomeKit doesn't mind which characteristic is added to which service type. I have integrated all characteristics (including Rotation Speed) under Service.Thermostat and I can change the Fan Speed using Siri Commands and the Rotation Speed shows up under the Thermostat device in most apps.
Unfortunately, the Home app in iOS 10 doesn't give you a graphical display for the Rotation Speed for the device because its assuming the device is a thermostat at the moment, but I can still say: "set the (thermostat name) rotation speed to 100" and control the Fan Speed that way.
Once "Air Conditioner" support is officially released and HAP-NodeJS is updated to recognise the new ServiceTypes, It should be much easier to shift all Characteristics under the single ServiceType.

- CoolingThreshold is very useful. I haven't had the need to use or change it yet, but its a great option to have.

- The error handling you added is great. Now homebridge can handle the sensible server communications properly.... Well mostly, most of the errors are coming from the sensibo server side from my testing.

I'd happily show you the changes I made to your code which give me the functionality I prefer. The changes I made are very minimal to be fair.
Let me know if you'd like to have a look.

Great job though man. The plugin is much more stable with your changes!!

**Comment by leoneleone** [comment]
```
        this.loadData();
        this.addService(Service.Thermostat);
        //this.addService(Service.Fan);
        //this.addService(Service.HumiditySensor);

        // AccessoryInformation characteristic
        // Manufacturer characteristic
        this.getService(Service.AccessoryInformation)
                .setCharacteristic(Characteristic.Manufacturer, "Sensibo");

        // Model characteristic
        this.getService(Service.AccessoryInformation)
                .setCharacteristic(Characteristic.Model, "version 0.2.0");

        // SerialNumber characteristic
        this.getService(Service.AccessoryInformation)
                .setCharacteristic(Characteristic.SerialNumber, "Pod ID: " + that.deviceid);

        //This will switch the Sensibo Pod ON and OFF.
        //Siri Command example: Turn on the "LivingRoom" Thermostat, Turn off the "Device Name", etc.
        this.getService(Service.Thermostat)
                .addCharacteristic(Characteristic.On)
                .on('get', function(callback) {
                        if (that.state.on=true)
                                callback(null, true);
                        else if (that.state.on=false)
                                callback(null, false);
                })
                .on('set', function(value, callback) {
                        callback();
                        if (value) {
                                that.state.on=true;
                        } else {
                                that.state.on=false;
                        }
                        that.platform.api.submitState(that.deviceid, that.state, function(data){
                                if (data !== undefined) {
                                        logStateChange(that)
                                }
                        });
                });





        // Current Relative Humidity characteristic
        this.getService(Service.Thermostat)
                .addCharacteristic(Characteristic.CurrentRelativeHumidity)
                .on('get', function(callback) {
                        callback(null, that.temp_humidity); // int value
                });

        // Rotation Speed characteristic
        this.getService(Service.Thermostat)
                .addCharacteristic(Characteristic.RotationSpeed)
                .on("get", function(callback) {
                        switch (that.state.fanLevel) {
                                case "low":
                                        callback(null, 25);
                                        break;
                                case "medium":
                                        callback(null, 50);
                                        break;
                                case "high":
                                        callback(null, 100);
                                        break;
                                case "auto":
                                        callback(null, 0);
                                        break;
                        }
                })
```
..... Etc

**Comment by bgottsch** [comment]
@leoneleone 

Great feedback, thanks!

- battery: I believe it's a implementation problem with iOS 10. This should be an easy fix.

- services: I agree, using two separate services is confusing and is a simple hack around the fact air conditioners did not exist in HomeKit. Since iOS 10 is still in beta, and Node-HAP has not been updated to support it, it's best to wait for a release so that the plugin can be modified to correctly show an air conditioner.

Quickly looking to your changes, I believe it's the path we should follow from now on. Still, iOS 10 is almost released. I think it's a good idea to wait for it's official release for us to modify anything.

Anyway, great changes also! Hope they release the official soon.

Regards,
Beno

**Comment by leoneleone** [comment]
Agreed Beno. 
iOS 10 shouldn't be too far away now. 

I've made the changes on my system because I prefer the one service. I'll let you know if I run into any problems with it, but it seems to be working great so far 🙂

**Comment by pdlove** [comment]
I've updated my local node-hap from the Homekit Accessory Simulator and I finally have cameras and door bells, but still no changes around air conditioners. It is only a month away from release, so they should have it soon.

**Comment by leoneleone** [comment]
@pdlove 
Amazing. 
You mean you've modified your HomeKitTypes file and added the new services and characteristics? Well the two you mentioned at least...

I wouldn't mind having a look. 
Maybe I can do a bit of tinkering too. Would love to get my nest cams working as cameras. I also have an August DoorBell Camera, but I think August is adding HomeKit support for that once the official release is out. 

Once we have the AirConditioner ServiceType details, it should be a simple and minimal change to the Sensibo plugin. 

I'll be sure to submit a pull request if you'd rather Beno or I make the needed changes 🙂

**Comment by leoneleone** [comment]
@pdlove 
Oh and have you looked through beta5 yet for the AirCon service type yet?  Or is all of this based on beta4?

**Comment by pdlove** [comment]
It was actually Beta 3 work. I just finally understood how KHaost did it and duplicated his process. I'm in the process of updating everything to beta 5 and will check again. I'll have everything updated in my fork of HAP-Nodejs tonight (5 hours from now) through Beta 5.

**Comment by bgottsch** [comment]
Nice work. I have the beta 5 running on my device and the simultor on my macOS 10.12 and I did not see any air conditioner stuff.

**Comment by pdlove** [comment]
I'm good with this branch. I don't think Apple is going to really have better Air Conditioner support in version 10. Any objections to bringing in the code and producing an updated npm? I'll do it this weekend unless someone says wait.

**Comment by leoneleone** [comment]
Good for me too 
I can submit another pull request later once iOS 10 is released

**Comment by leoneleone** [comment]
Has the iOS 10 GM added the missing Services? Air-Con, Purifier, etc.

Would be good to integrate any new info into the plugin 🙂

**Comment by pdlove** [comment]
No new services since my last upload to HAP-NodeJS.
It looks like they didn't follow through. (Imagine That)

**Comment by leoneleone** [comment]
Maybe they're waiting until those devices are "officially" out there on the market. It's a shame they didn't just add the backbone for those other new services.

**Comment by pdlove** [comment]
I'm going to see what my Ecobee does after it updates for Windows 10. That will help identify if it's just a hidden service.

**Pull request merged**
